# You shouldn't need to change this
# User-defined configuration is in userconf.yml

# Directories where the masks are read from on the RDSF
# Relative to the RDSF mount point
label_dirs:
 - "1Felix and Rich make models/Training dataset Tiffs/Training set 1"
 - "1Felix and Rich make models/Training dataset Tiffs/Training set 2"
 - "1Felix and Rich make models/Training dataset Tiffs/Training set 3 (base of jaw)"

wahabs_3d_tifs: "1Felix and Rich make models/wahabs_scans"
felix_labels_dir_2: "1Felix and Rich make models/Training dataset Tiffs/Training set 2"
wahab_labels_dir: "1Felix and Rich make models/Training dataset Tiffs/Training set 1"

# Where random stuff from the scripts should go, relative to the root of the repository
script_output: "script_output/"
boring_script_output: "script_output/boring_stuff/"

# This fish is in two training sets, so we need to remove it from one of them
duplicate_ids:
 - 39