name: zebrafish_jaw_segmentation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cudatoolkit=11.8
  - cudnn=8.1.0
  - pandas
  - pip
  - pytorch=2.2
  - pytorch-cuda=11.8
  - torchvision
  - monai
  - numpy
  - scikit-learn
  - matplotlib
  - tqdm
  - jupyter
  - pydicom
  - tifffile
  - trimesh
  - scikit-image
  - pytest
  - pylint
  - black
  - pyyaml
  - numpy-stl
  - prettytable
  - tabulate
  - mypy
  - types-PyYAML
  - pdflatex
  - pip:
      - pickle-mixin
      - torchio
      - opencv-python