name: zebrafish_jaw_segmentation
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - cudatoolkit
  - cudnn
  - pandas
  - pip
  - pytorch
  - torchvision
  - monai
  - numpy
  - scikit-learn
  - matplotlib
  - tqdm
  - jupyter
  - pydicom
  - tifffile
  - trimesh
  - scikit-image
  - pytest
  - pylint
  - black
  - pyyaml
  - pip:
      - pickle-mixin
      - torchio
      - opencv-python