# User-defined configuration file; things here depend on where your files are etc.
rdsf_dir: '/home/mh19137/zebrafish_rdsf/'
dicom_dir: '/home/mh19137/zebrafish_jaw_segmentation/dicoms/'

# Options for the model that you might want to change
window_size: 192,192,192  # Comma-separated ZYX. Needs to be large enough to hold the whole jaw
patch_size: 128,128,128
learning_rate: 0.05
optimiser: "Adam"  # Must be one of the torch.optim optimisers
batch_size: 16
epochs: 25
lr_lambda: 1.0 # Exponential decay factor
loss: "monai.losses.TverskyLoss"
loss_options: {"include_background": false, "to_onehot_y": true, "alpha": 1, "beta": 1, "softmax": true}

# RNG seeds
# Note that this still doesn't guarantee reproducibility,
# since the dataloaders and probably some algorithms/other things have different sources
# of randomness
# But (hopefully) it should mean our model is initialised the same way each time
torch_seed: 0
test_train_seed: 1

model_params:
  # Things you probably won't need to change - I just kept them here to keep all the params in one place
  spatial_dims: 3
  n_classes: 2  # n bones + background
  in_channels: 1  # Our images are greyscale

  # Things you might want to change
  n_layers: 6  # 6?
  n_initial_filters: 6  # 6 would be sensible
  kernel_size: 3  # 7
  stride: 2  # 2
  dropout: 0.0