name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        activate-environment: zebrafish_jaw_segmentation

    - name: Run Unit Tests
      run: |
        python -m pytest fishjaw/test/test_unit

    - name: Run Integration Tests
      run: |
        python -m pytest fishjaw/test/test_integration