name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # NB I kept having mamba issues so this is how i'm doing it
    - name: Set up environment
      run: |
        ./install_env.sh

    - name: Run Unit Tests
      run: |
        python -m pytest fishjaw/test/test_unit

    - name: Run Integration Tests
      run: |
        python -m pytest fishjaw/test/test_integration