name: UT/IT

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        run: uv sync

    - name: Run Unit Tests
      run: |
        uv run pytest fishjaw/test/test_unit

    - name: Run Integration Tests
      run: |
        uv run pytest fishjaw/test/test_integration