name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        conda env create -f environment.yml
        conda activate zebrafish_jaw_segmentation

    - name: Run Unit Tests
      run: |
        conda activate zebrafish_jaw_segmentation
        python -m pytest fishjaw/test/test_unit

    - name: Run Integration Tests
      run: |
        conda activate zebrafish_jaw_segmentation
        python -m pytest fishjaw/test/test_integration