name: System Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Run Tests
      run: uv run pytest fishjaw/test/test_system
